### PR TITLE
Fixes issue with any object created with prototype set to null

### PR DESCRIPTION
**Pull request by combizs**
Any object created with prototype = null will crash server.
Use objectHasProp to use Object hasOwnProperty method.

### CODE REVIEW

**Comment by mcollina** [comment]
Tests are failing with this PR, and also can you add a unit test for this case?

**Comment by davidmarkclements** [comment]
I bet it's faster to check `n.hasOwnProperty === undefined`
instead - if it's undefined then you can do a `k in n` , if it's not then use as normal (if we want to be sure we can a typeof check for function instead of check for undefined value)

**Comment by combizs** [comment]
The issue is more along the lines of getting an object that was created with a prototype of null, so hasOwnProperty was failing.  With that in mind, I thought it would be best to borrow the hasOwnProperty from an Object prototype and let it run its course.

**Comment by davidmarkclements** [comment]
Yeah for sure, understood.

But the reason it fails is because a null prototype leads to a missing function (hasOwnProperty). Your solution is conventional and fully normative, no problems there. However, is there a faster way (pino philosophy: keep logging overhead to an absolute minimum). 

Is it in fact faster to achieve the same using the approach as described in my prior comment? We can find out by trying both ways and running benchmarks

**Comment by combizs** [comment]
@davidmarkclements, Ran the benchmarks and it barely made a difference.  But, just to be clear, does this illustrate your example?

```javascript
n[k] = ((n.hasOwnProperty === undefined ? k in n : n.hasOwnProperty(k)) && nv === ov) || nv === undefined ? n[k] : nv
```

**Comment by davidmarkclements** [comment]
yep that's what I meant - if there's no discernible difference then keeping to convention is best

thank you for the PR!

**Comment by davidmarkclements** [comment]
v2.2.1 released

**Pull request merged**
